### ISSUE TITLE
Segmentation fault in --merge-list

### ISSUE THREAD

**Issue by aksarkar** [chrchang/plink-ng#33]
I am trying to merge single chromosome files (converted to .bed after imputation to Thousand Genomes Phase 1), but running into a segfault in merge_fam_id_scan.

The following works:

```
$ plink --memory 4000 --bfile 58C_01 --bmerge 58C_02 --make-bed --out test
PLINK v1.90b3.38 64-bit (7 Jun 2016)       https://www.cog-genomics.org/plink2
(C) 2005-2016 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to test.log.
Options in effect:
  --bfile 58C_01
  --bmerge 58C_02
  --make-bed
  --memory 4000
  --out test

48251 MB RAM detected; reserving 4000 MB for main workspace.
1478 people loaded from 58C_01.fam.
1478 people to be merged from 58C_02.fam.
Of these, 0 are new, while 1478 are present in the base dataset.
711902 markers loaded from 58C_01.bim.
772778 markers to be merged from 58C_02.bim.
Of these, 772778 are new, while 0 are present in the base dataset.
Warning: Variants 'rs111748052|chr01|886817|886817|CATTTT' and
'rs10465241|chr01|886817|886817|T' have the same position.
Warning: Variants 'rs201179857|chr01|1036876|1036876|TA' and
'rs11578997|chr01|1036876|1036876|A' have the same position.
Warning: Variants 'rs144847714|chr01|3765424|3765424|GT' and
'rs10492943|chr01|3765424|3765424|T' have the same position.
1319 more same-position warnings: see log file.
Performing single-pass merge (1478 people, 1484680 variants).
Merged fileset written to test-merge.bed + test-merge.bim + test-merge.fam .
1484680 variants loaded from .bim file.
1478 people (739 males, 739 females) loaded from .fam.
Using 1 thread (no multithreaded calculations invoked).
Before main variant filters, 1478 founders and 0 nonfounders present.
Calculating allele frequencies... done.
Total genotyping rate is 0.868617.
1484680 variants and 1478 people pass filters and QC.
Note: No phenotypes present.
--make-bed to test.bed + test.bim + test.fam ... done.
```

But using --merge-list crashes with a segfault:

```
$ plink --memory 4000 --bfile 58C_01 --merge-list <(echo 58C_02) --make-bed --out test2
$ plink --memory 4000 --merge-list <(echo 58C_01; echo 58C_02) --make-bed --out test2
```

Both ways fail with the same gdb backtrace:

```
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-90.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /broad/compbio/aksarkar/.local/bin/plink...(no debugging symbols found)...done.
(gdb) target core core.22642
target core core.22642
[New Thread 22642]
[Thread debugging using libthread_db enabled]
Core was generated by `plink --memory 4000 --merge-list /dev/fd/63 --make-bed --out test2'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000008362b1 in strlen ()
(gdb) bt
bt
#0  0x00000000008362b1 in strlen ()
#1  0x000000000049ddbd in merge_fam_id_scan(char*, char*, unsigned int, unsigned long*, unsigned int*, unsigned int*, ll_entry_struct**, unsigned long long*, unsigned int*, unsigned int*, unsigned int*) ()
#2  0x00000000004c80cd in merge_datasets(char*, char*, char*, char*, char*, char*, char*, char*, char*, unsigned long long, unsigned int, unsigned int, unsigned long long, Chrom_info*) ()
#3  0x0000000000404101 in plink(char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, two_col_params_struct*, two_col_params_struct*, char*, char*, char*, char*, two_col_params_struct*, two_col_params_struct*, two_col_params_struct*, two_col_params_struct*, two_col_params_struct*, char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, char*, unsigned int, double, double, double, double, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, int, char*, unsigned int, unsigned int, Chrom_info*, Oblig_missing_info*, Family_info*, double, double, unsigned int, unsigned int, double, double, double, double, double, double, double, double, unsigned long long, unsigned long long, unsigned long long, unsigned int, unsigned long, unsigned int, unsigned long, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, double, double, Homozyg_info*, Cluster_info*, unsigned int, unsigned int, Set_info*, Ld_info*, Epi_info*, Clump_info*, Rel_info*, Score_info*, uns---Type <return> to continue, or q <return> to quit---

igned int, unsigned int, unsigned int, unsigned int, int, int, int, char*, char*, char*, range_list_struct*, unsigned int, unsigned int, range_list_struct*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, double, unsigned int, unsigned int, range_list_struct*, range_list_struct*, double, double, double, unsigned int, double, unsigned int, Aperm_info*, unsigned int, unsigned long, unsigned int, double, unsigned int, double, range_list_struct*, unsigned int, unsigned int, unsigned int, int, ll_str_struct**) ()
#4  0x0000000000415fdf in main ()
```

**Comment by chrchang** [comment]
The current --merge-list implementation scans the file twice, so an input stream like "<(echo 58C_02)" won't work.

There are too many situations where it's useful to make 2 (or occasionally more) passes over the input data to justify supporting input streams everywhere.  The best I can do is document which flags support input streams and which flags don't, once the implementation is finalized.

**Comment by Wainberg** [comment]
In the latest stable build (v1.90b6.24, 6 June 2021), --merge-list still segfaults when given an input stream rather than a file. As @chrchang says, it's fine to not support input streams for some operations, but you can't just segfault when you get one!

**Comment by chrchang** [comment]
Fair enough.  This should be fixed in today's dev build (and will be fixed in the next stable build).

**Comment by Wainberg** [comment]
Awesome, thanks!
